### PR TITLE
PLAT-1174: Remove form-group component

### PR DESCRIPTION
**Pull request by chavlji**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1174)

### CODE REVIEW

**Review by mihaelpalfi — COMMENTED** [review]
For me all the containers, tooltip, drawer, popover... now have a horizontal scroll. 

image

**Comment by chavlji** [comment]
@mihaelpalfi it will be addressed in this ticket:
https://reciprocitylabs.atlassian.net/browse/PLAT-1472

**Comment by chavlji** [comment]
Margins reverted and it should be ok now.

**Review by mihaelpalfi — APPROVED** [review]
Tested and it looks ok.

**Review by f-jauregui — APPROVED** [review]
Tested and it's all working 👌

**Pull request merged**
