### PR TITLE
PLAT-1156: Add min width to notification component

### PR DESCRIPTION
**Pull request by mihaelpalfi**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1156)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by mplesec — APPROVED** [review]
Approving, but this should really have some tests accompanying it...

**Comment by mihaelpalfi** [comment]
> Approving, but this should really have some tests accompanying it...

Are not the visual regression test that check that?

**Comment by mplesec** [comment]
@mihaelpalfi apparently not since none have been updated for this fix 😅

**Review by chavlji — APPROVED** [review]
👍🏻 Agree about the test.

**Pull request merged**
