### PR TITLE
PLAT-1691: Updated zen-option mouseover hover style and remove keyboard focused style when mouseover

### PR DESCRIPTION
**Pull request by f-jauregui**
⚠️ Not sure I totally understood the issue in this ticket but let's see if this solve it.

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1691)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Comment by homer0** [comment]
I don't think this is working properly:

image

I believe that the scroll that happens when the focus changes, it's re-triggering the mouse event after you "unselected" all siblings.

I think the solution should be something like: "when you use the arrows, a flag that allows the style to change on mouse over is set to `false` and cannot be changed for ~1sec, and when there's a mouse move, the flag changes to `true`". Not sure if the the "waiting" is necessary, but if the scroll re triggers the mouse move, it would be the same situation.

**Comment by chavlji** [comment]
Yeah. We should have private vars `keyboardFocusedItem` and `mouseFocusedItem`. They should mutually exclude:
- If user mouseover item, `keyboardFocusItem` is set to `null`.
- If `mouseFocusedItem` is set and user presses `down` key, `keyboardFocusedItem` becomes next item from `mouseFocusedItem` and `mouseFocusedItem` is set to null.
- If `mouseMove` or `mouseOver` occurs on item while `keyboardFocusedItem` is set, `keyboardFocusedItem` should be set to `null` and `mouseFocusedItem` is set to mouse hovering item.

**Comment by homer0** [comment]
@f-jauregui I added the `WIP!` label, as the solution would be different as the one in the PR.

**Comment by chavlji** [comment]
Nice! It works as expected!

One NIT: I get this linter complaints:
Screenshot 2021-04-12 at 16 09 57

**Review by chavlji — APPROVED** [review]
Nice! It works as expected!

One NIT: I get this linter complaints:
Screenshot 2021-04-12 at 16 09 57

**Comment by homer0** [comment]
I hate to be that guy, but...there's still a bug :P:

https://user-images.githubusercontent.com/6949310/114429064-54cab280-9b93-11eb-9669-a00696dc5e2b.mov

If, for some reason, the mouse is over an item when you move with the keyboard, is that items enters the viewport again, it steals the focus from the keyboard. In the case of the video, I couldn't choose the first option with the keyboard.

**Comment by chavlji** [comment]
Is this fixed? It looks to me that it's working as expected... what baffles me is that there's only 1 commit. Please add fixes after reviews as a separate commit so it's easier to review changes.

**Review by mihaelpalfi — APPROVED** [review]
Works as expected!

**Comment by f-jauregui** [comment]
> @f-jauregui Is this fixed? It looks to me that it's working as expected... what baffles me is that there's only 1 commit. Please add fixes after reviews as a separate commit so it's easier to review changes.

Yes. Sorry about that, was mainly to keep the commit clean. But just changing the mouseover to mousemove did the trick.

**Pull request merged**
