### PR TITLE
BAN-113: Dropdown new props

### PR DESCRIPTION
**Pull request by chavlji**
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-113)

### CODE REVIEW

**Review by mplesec — APPROVED** [review]
Very nice 👍

**Review by mihaelpalfi — APPROVED** [review]
Nice. Works as expected.

**Review by f-jauregui — CHANGES_REQUESTED** [review]
Looks awesome, just a little thing.
When I turn borderless on, text aligns to top:

Captura de Pantalla 2020-12-15 a la(s) 08 33 41

**Review by f-jauregui — APPROVED** [review]
Great job!

**Pull request merged**
