### PR TITLE
PLAT-1805: Progress tracker labels now have white-space nowrap style

### PR DESCRIPTION
**Pull request by f-jauregui**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1805)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by chavlji — APPROVED** [review]
Nice, that you've also corrected those typos!

**Review by mihaelpalfi — APPROVED** [review]
Works. From where are this typos? Looks like what i merged.

**Comment by f-jauregui** [comment]
> Works. From where are this typos? Looks like what i merged.

@mihaelpalfi now that I rebased they're gone

**Pull request merged**
