### PR TITLE
PLAT-1609: zen-button: Add size prop

### PR DESCRIPTION
**Pull request by chavlji**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1609)

#### Description
As per JIRA ticket

### CODE REVIEW

**Review by f-jauregui — APPROVED** [review]
Tested and it's working perfectly

**Review by homer0 — APPROVED** [review]
🤘

**Review by mihaelpalfi — APPROVED** [review]
Works. Good job.

**Pull request merged**
