### PR TITLE
PLAT-1607: Remove size lg from avatar-icon

### PR DESCRIPTION
**Pull request by f-jauregui**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1607)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by mihaelpalfi — COMMENTED** [review]
Good work. But i think you should not remove size lg from type IconSize. It is use also for the zen-icon component and from the wireframes the icons has 3 sizes.
image

Maybe it would be better to create a new type like AvatarIconSize...

**Comment by f-jauregui** [comment]
> Good work. But i think you should not remove size lg from type IconSize. It is use also for the zen-icon component and from the wireframes the icons can have 3 sizes.
> image
> 
> Maybe it would be better to create a new type like AvatarIconSize...

Good catch, @mihaelpalfi. I'll correct that.

**Review by homer0 — APPROVED** [review]
🤘

Not a blocker, but I would recommend you to avoid plural names for union types; the type is one, the values are multiples.

**Review by mihaelpalfi — APPROVED** [review]
Good work. Just change the types to singular (AvatarIconSize and IconSize).

**Pull request merged**
