### PR TITLE
PLAT-1659: Validate the use of EM units on ZenUI

### PR DESCRIPTION
**Pull request by chavlji**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1659)

#### Description
As per JIRA ticket

These units should remain in em:
Screenshot 2021-04-01 at 12 32 21

### CODE REVIEW

**Review by f-jauregui — APPROVED** [review]
Looks good to me. Nice cleanup.

**Review by homer0 — APPROVED** [review]
🤘

**Comment by homer0** [comment]
@chavlji Can you change the message of the `refactor` commit to `fix`? that way it will generate a release.

**Review by mihaelpalfi — APPROVED** [review]

**Pull request merged**
