### PR TITLE
PLAT-1004: ZenTable sticky header

### PR DESCRIPTION
**Pull request by mplesec**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1004)

#### Description
PR adds sticky header support to ZenTable.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Comment by leferreyra** [comment]
Looking good!
Will pull and try in a few mins.

Would be awesome to have the same setup we had in ZenLib where a branch-specific deployment of storybook was linked on each PR, I found that really useful while looking at PRs. We already have the ZenBot user and all that jazz and the scripts to post to GitHub ;)
Eg. https://github.com/reciprocity/zenlib/pull/94#issuecomment-700598771

**Comment by leferreyra** [comment]
Works like a charm
table

**Review by leferreyra — APPROVED** [review]
LGTM

**Comment by chavlji** [comment]
I see one strange glitch. When I scroll header is jumping by 1px up and down (as it would be out of sync with the rest of the scroll area). And because of that sometimes the content leaks above the table:
Screenshot 2021-01-28 at 10 01 18
But anyway... this can be tackled in the next pr. Let's just merge this one, because it's good enough.

**Review by chavlji — APPROVED** [review]

**Comment by mplesec** [comment]
@chavlji very strange, to me it only shows up when I zoom in the page. Wish I knew for sure what the cause is.

**Pull request merged**
