### PR TITLE
PLAT-1586: Fix table sticky background

### PR DESCRIPTION
**Pull request by mihaelpalfi**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1586)

- fixes the issue that rows z-index header gets messed up and table header sticky is not shown above the rows. (basicly the transform: scale(1) hack)
image

- refactored the sticky part so that the param is reflective now and class is applied also to children.

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Comment by chavlji** [comment]
We should avoid using z-indexes on everything except popovers and modals.

Here's an example of such problems with this version:
Row that holds dropdown has z-index 2. Header also has z-index 2. Because header is listed after row in the dom tree, it is rendered above row. And since dropdown is on same layer as row (row is promoted to layer because of z-index: 2), it is covered by the header:

Screenshot 2021-03-25 at 16 30 58

There are only 2 solutions to this problem:
1. Attach modals, popovers,... directly to body (but that might mess reactive frameworks)
2. Don't use z-indexes except for modals, popovers,...

**Comment by chavlji** [comment]
Another example of this problem:
If ordinary row has dropdown, both detailed row and header covers dropdown.
Screenshot 2021-03-25 at 16 42 36

**Comment by mihaelpalfi** [comment]
> Another example of this problem:
> If ordinary row has dropdown, both detailed row and header covers dropdown.
> Screenshot 2021-03-25 at 16 42 36

This second one is a problem yes. Will check further.

**Review by chavlji — APPROVED** [review]
👍

**Pull request merged**
