### PR TITLE
PLAT-1690: Fix dropdown set menu width height

### PR DESCRIPTION
**Pull request by mihaelpalfi**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1690)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by homer0 — APPROVED** [review]
image

Are the tests failing because you need to update them?

**Comment by homer0** [comment]
@mihaelpalfi @chavlji @f-jauregui this is a good example of a special case we can come across in the future: The change is breaking, because the prop used to be a number and didn't require the unit to be specified, but since it was tied to a bug, we can release it as a fix

**Comment by mihaelpalfi** [comment]
> Are the tests failing because you need to update them?

@homer0 Hmm they dont if i run them localy.

**Pull request merged**
