### PR TITLE
PLAT-1547: update vrt for modal

### PR DESCRIPTION
**Pull request by Donaab**
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1547)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Comment by Donaab** [comment]
Something weird is happening in my docker container so my screenshots are not good.

**Comment by Donaab** [comment]
@chavlji @mihaelpalfi Now screenshots are ok so you can review.

**Review by chavlji — APPROVED** [review]
Awesome, Nada! 😎

**Review by mihaelpalfi — APPROVED** [review]
Great work. Probably would need quite some time to figure this out. :)

**Pull request merged**
