### PR TITLE
QUICK-FIX: Run VRTs only in headless mode

### PR DESCRIPTION
**Pull request by mplesec**
#### Description
PR ensures visual regression tests are run only in headless mode. Also adds a command to update snapshots.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by chavlji — APPROVED** [review]

**Comment by chavlji** [comment]
Works as expected. `test:e2e` failed at first, but after I ran `test:e2e:update` it passed both tests.
Btw, is it normal that I have to manually start tests inside chromium on `test:e2e:interactive`?
Screenshot 2021-01-12 at 15 45 43

**Comment by Donaab** [comment]
@chavlji  Yes it is expected that in interactive mode you want to work with one test and you want to choose that test.

**Review by Donaab — APPROVED** [review]

**Comment by mplesec** [comment]
@chavlji why did it fail?

**Comment by chavlji** [comment]
Hm yeah, not sure exactly... new screenshot looks pretty much the same to old one:
Screenshot 2021-01-12 at 15 55 19
But old one fails and new one passes...

**Comment by mplesec** [comment]
@chavlji what does the diff_output produce for this? 😅

**Comment by Donaab** [comment]
@mplesec @chavlji I think only when you enable run in docker we should look at how stable tests are.

**Pull request merged**
