### PR TITLE
QUICK-FIX: Pin dependencies

### PR DESCRIPTION
**Pull request by mplesec**
#### Description
Due to https://github.com/reciprocity/zen-ui/pull/222, would be a good idea to avoid these kinds of problems in the future.

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

### CODE REVIEW

**Review by chavlji — APPROVED** [review]

**Comment by f-jauregui** [comment]
I disagree on this.
One thing is to avoid minor version changes (^), another one is to avoid all patches (~). What about security issues in the future? Shall we update update dependencies manually?
Also I don't understand why `"@babel/preset-typescript": "7.13.0"` was pinned before. Isn't this caused #222?

**Comment by mplesec** [comment]
Using a bot makes more sense regarding security, like we have on ZenGRC. And we also see it in the logs.

**Comment by mplesec** [comment]
Regarding the dependency, it wasn't explicitly specified in `package.json`.

**Comment by chavlji** [comment]
@mplesec  But this current error with @babel/core probably appeared because we allowed minor version changes on that packages? It probably wouldn't happen if we'd allow just patch version updates?

**Comment by mplesec** [comment]
I wouldn't rely on probably for this 😅 I don't think we're risking much tbh. And either a bot or some alerting can be set up in like an hour anyway.

**Pull request merged**
